name: SendMessage build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.MicrosoftTeams.SendMessage/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.MicrosoftTeams.SendMessage
      env_var_name_1: TestTeams_ClientId
      env_var_name_2: TestTeams_ClientSecret
      env_var_name_3: TestTeams_TestUserId
      env_var_name_4: TestTeams_Username
      env_var_name_5: TestTeams_Password
      env_var_name_7: TestTeams_TenantId
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.TESTTEAMS_CLIENTID}}
      env_var_value_2: ${{ secrets.TESTTEAMS_CLIENTSECRET }}
      env_var_value_3: ${{ secrets.TESTTEAMS_TESTUSERID }}
      env_var_value_4: ${{ secrets.TESTTEAMS_USERNAME }}
      env_var_value_6: ${{ secrets.TESTTEAMS_PASSWORD }}
      env_var_value_7: ${{ secrets.TESTTEAMS_TENANTID }}